name: Run test

on:
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened]
  release:
    types: [published]
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.19.0'
      - name: Run test 
        run: make test